"""Reject a few classes of accidental private material before publication."""
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
CHECKED_SUFFIXES = {'.command', '.java', '.json', '.py', '.sh', '.yml', '.yaml'}
PRIVATE_MARKERS = ('/Users/eric', 'Generated by Codex', 'Generated by ChatGPT', 'Generated by Claude')


def tracked_files():
    result = subprocess.run(
        ['git', 'ls-files'], cwd=ROOT, check=True, text=True, capture_output=True
    )
    return [ROOT / name for name in result.stdout.splitlines()]


def main():
    errors = []
    checker = Path(__file__).resolve()
    for path in tracked_files():
        if path == checker or path.suffix not in CHECKED_SUFFIXES or not path.is_file():
            continue
        text = path.read_text(errors='replace')
        for marker in PRIVATE_MARKERS:
            if marker in text:
                errors.append(f'{path.relative_to(ROOT)} contains {marker!r}')
    history = subprocess.run(
        ['git', 'log', '-E', '--format=%B'], cwd=ROOT, check=True,
        text=True, capture_output=True,
    ).stdout
    if any(line.lower().startswith('co-authored-by:') for line in history.splitlines()):
        errors.append('Git history contains a Co-authored-by trailer')
    if errors:
        print('\n'.join(errors), file=sys.stderr)
        return 1
    print(f'Public tree check passed for {len(tracked_files())} tracked files.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
